#pragma once
#define _CRT_SECURE_NO_WARNINGS
#include <iostream>
#include <fstream>
#include <vector>
#include <string>
#include <sstream>
#include <thread>
#include <mutex>
#include <set>
#include <random>
#include <algorithm>
#include <numeric>
#include <xgboost/c_api.h>
#include <iomanip>
#include <functional>
#define NOMINMAX 
#include <Windows.h>
#include <cmath>